/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Mentor } from "./Mentor";
import { MentorCountArgs } from "./MentorCountArgs";
import { MentorFindManyArgs } from "./MentorFindManyArgs";
import { MentorFindUniqueArgs } from "./MentorFindUniqueArgs";
import { CreateMentorArgs } from "./CreateMentorArgs";
import { UpdateMentorArgs } from "./UpdateMentorArgs";
import { DeleteMentorArgs } from "./DeleteMentorArgs";
import { LessonFindManyArgs } from "../../lesson/base/LessonFindManyArgs";
import { Lesson } from "../../lesson/base/Lesson";
import { ReviewFindManyArgs } from "../../review/base/ReviewFindManyArgs";
import { Review } from "../../review/base/Review";
import { MentorService } from "../mentor.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Mentor)
export class MentorResolverBase {
  constructor(
    protected readonly service: MentorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Mentor",
    action: "read",
    possession: "any",
  })
  async _mentorsMeta(
    @graphql.Args() args: MentorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Mentor])
  @nestAccessControl.UseRoles({
    resource: "Mentor",
    action: "read",
    possession: "any",
  })
  async mentors(@graphql.Args() args: MentorFindManyArgs): Promise<Mentor[]> {
    return this.service.mentors(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Mentor, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Mentor",
    action: "read",
    possession: "own",
  })
  async mentor(
    @graphql.Args() args: MentorFindUniqueArgs
  ): Promise<Mentor | null> {
    const result = await this.service.mentor(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Mentor)
  @nestAccessControl.UseRoles({
    resource: "Mentor",
    action: "create",
    possession: "any",
  })
  async createMentor(@graphql.Args() args: CreateMentorArgs): Promise<Mentor> {
    return await this.service.createMentor({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Mentor)
  @nestAccessControl.UseRoles({
    resource: "Mentor",
    action: "update",
    possession: "any",
  })
  async updateMentor(
    @graphql.Args() args: UpdateMentorArgs
  ): Promise<Mentor | null> {
    try {
      return await this.service.updateMentor({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Mentor)
  @nestAccessControl.UseRoles({
    resource: "Mentor",
    action: "delete",
    possession: "any",
  })
  async deleteMentor(
    @graphql.Args() args: DeleteMentorArgs
  ): Promise<Mentor | null> {
    try {
      return await this.service.deleteMentor(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Lesson], { name: "lessons" })
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "read",
    possession: "any",
  })
  async findLessons(
    @graphql.Parent() parent: Mentor,
    @graphql.Args() args: LessonFindManyArgs
  ): Promise<Lesson[]> {
    const results = await this.service.findLessons(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Review], { name: "reviews" })
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "read",
    possession: "any",
  })
  async findReviews(
    @graphql.Parent() parent: Mentor,
    @graphql.Args() args: ReviewFindManyArgs
  ): Promise<Review[]> {
    const results = await this.service.findReviews(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
